apiVersion: linkerd.io/v1alpha2
kind: ServiceProfile
metadata:
  name: catalog-service.e-commerce.svc.cluster.local
  namespace: e-commerce
spec:
  routes:
  - name: get-products
    condition:
      method: GET
      pathRegex: "/products"
    timeout: 10s
    retryBudget:
      retryRatio: 0.2
      minRetriesPerSecond: 10
      ttl: 10s
  - name: get-product
    condition:
      method: GET
      pathRegex: "/products/[^/]+"
    timeout: 5s
    isRetryable: true
---
apiVersion: linkerd.io/v1alpha2
kind: ServiceProfile
metadata:
  name: cart-service.e-commerce.svc.cluster.local
  namespace: e-commerce
spec:
  routes:
  - name: get-cart
    condition:
      method: GET
      pathRegex: "/cart/[^/]+"
    timeout: 10s
  - name: add-to-cart
    condition:
      method: POST
      pathRegex: "/cart/[^/]+/add"
    timeout: 15s
    isRetryable: false  # POST не идемпотентен
  - name: checkout
    condition:
      method: POST
      pathRegex: "/cart/[^/]+/checkout"
    timeout: 30s
    isRetryable: false
---
apiVersion: linkerd.io/v1alpha2
kind: ServiceProfile
metadata:
  name: payment-service.e-commerce.svc.cluster.local
  namespace: e-commerce
spec:
  routes:
  - name: process-payment
    condition:
      method: POST
      pathRegex: "/payment/process"
    timeout: 30s
    isRetryable: false  # Платежи не должны повторяться
  - name: get-payment
    condition:
      method: GET
      pathRegex: "/payment/[^/]+"
    timeout: 5s
    isRetryable: true
  retryBudget:
    retryRatio: 0.1  # Низкий процент retry для платежей
    minRetriesPerSecond: 5
    ttl: 10s