apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: e-commerce
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    
    scrape_configs:
    # Сбор метрик с сервисов
    - job_name: 'e-commerce-services'
      kubernetes_sd_configs:
      - role: pod
        namespaces:
          names:
          - e-commerce
      relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_app]
        action: keep
        regex: (catalog|cart|payment)
      - source_labels: [__meta_kubernetes_pod_label_app]
        target_label: service
      - source_labels: [__meta_kubernetes_pod_label_version]
        target_label: version
      - target_label: __address__
        replacement: '${1}:5000'
        source_labels: [__meta_kubernetes_pod_ip]
      - target_label: __metrics_path__
        replacement: '/metrics'
    
    # Сбор метрик с Istio
    - job_name: 'istio-mesh'
      kubernetes_sd_configs:
      - role: endpoint
        namespaces:
          names:
          - istio-system
      relabel_configs:
      - source_labels: [__meta_kubernetes_service_name]
        action: keep
        regex: istio-telemetry
    
    # Сбор метрик с Envoy sidecar
    - job_name: 'envoy-stats'
      metrics_path: /stats/prometheus
      kubernetes_sd_configs:
      - role: pod
        namespaces:
          names:
          - e-commerce
      relabel_configs:
      - source_labels: [__meta_kubernetes_pod_container_name]
        action: keep
        regex: istio-proxy
      - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
        action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:15090
        target_label: __address__
    
    # Сбор метрик с Linkerd
    - job_name: 'linkerd-proxy'
      kubernetes_sd_configs:
      - role: pod
        namespaces:
          names:
          - e-commerce
      relabel_configs:
      - source_labels: [__meta_kubernetes_pod_container_name]
        action: keep
        regex: linkerd-proxy
      - source_labels: [__address__]
        action: replace
        target_label: __address__
        regex: ([^:]+)(?::\d+)?
        replacement: $1:4191