apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: e-commerce
  labels:
    app: gateway
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gateway
      version: v1
  template:
    metadata:
      labels:
        app: gateway
        version: v1
      annotations:
        config.linkerd.io/skip-inbound-ports: "5000"
    spec:
      serviceAccountName: api-gateway
      containers:
      - name: gateway
        image: localhost:5001/api-gateway:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
          name: http
        env:
        - name: PORT
          value: "5000"
        - name: CATALOG_SERVICE_URL
          value: "http://catalog-service:5001"
        - name: CART_SERVICE_URL
          value: "http://cart-service:5002"
        - name: PAYMENT_SERVICE_URL
          value: "http://payment-service:5003"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: e-commerce
  labels:
    app: gateway
spec:
  type: ClusterIP
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
    name: http
  selector:
    app: gateway