apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service-v1
  namespace: e-commerce
  labels:
    app: payment
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment
      version: v1
  template:
    metadata:
      labels:
        app: payment
        version: v1
      annotations:
        config.linkerd.io/skip-inbound-ports: "5003"
    spec:
      serviceAccountName: payment-service
      containers:
      - name: payment
        image: localhost:5001/payment-service:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5003
          name: http
        env:
        - name: PORT
          value: "5003"
        - name: SERVICE_VERSION
          value: "v1"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 5003
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5003
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service-v2
  namespace: e-commerce
  labels:
    app: payment
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
      version: v2
  template:
    metadata:
      labels:
        app: payment
        version: v2
      annotations:
        config.linkerd.io/skip-inbound-ports: "5003"
    spec:
      serviceAccountName: payment-service
      containers:
      - name: payment
        image: localhost:5001/payment-service:v2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5003
          name: http
        env:
        - name: PORT
          value: "5003"
        - name: SERVICE_VERSION
          value: "v2"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 5003
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5003
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: e-commerce
  labels:
    app: payment
spec:
  type: ClusterIP
  ports:
  - port: 5003
    targetPort: 5003
    protocol: TCP
    name: http
  selector:
    app: payment