apiVersion: v1
kind: ServiceAccount
metadata:
  name: cart-service
  namespace: e-commerce
  labels:
    app: cart
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: catalog-service
  namespace: e-commerce
  labels:
    app: catalog
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: payment-service
  namespace: e-commerce
  labels:
    app: payment
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: notification-service
  namespace: e-commerce
  labels:
    app: notification
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-gateway
  namespace: e-commerce
  labels:
    app: gateway